### ISSUE TITLE
Why we must duplicate params validation in view specs?

### ISSUE THREAD

**Issue by sovetnik** [hanami/bookshelf#1]
bookshelf/spec/web/views/books/new_spec.rb

Maybe we can access them from create action or separate in another file which can be required in both spec and action?

In this way is possible situation when we change params validation in action but not change in this spec. Then will get a passing spec but uncovered action behaviour.

**Comment by mereghost** [comment]
@sovetnik the validation block there is just test if the  template can render the errors. @cllns just set up some random validations and made sure they failed so [this block](https://github.com/hanami/bookshelf/blob/master/apps/web/templates/books/new.html.erb#L3) could be tested.

**Comment by mereghost** [comment]
BTW feel free to join us as https://gitter.im/hanami/chat so we can address your questions way faster. =)

**Comment by sovetnik** [comment]
@mereghost already there ;)

**Comment by cllns** [comment]
Fixed in #14, specifically: https://github.com/hanami/bookshelf/commit/504c94aca4a77c7f7fa67bb9640a55cc89fc2fb4 

(It had been long removed from the Getting Started guide, but it wasn't reflected in this repo. until #14)
